### ISSUE TITLE
Make systems non-singleton objects

### ISSUE THREAD

**Issue by zachrammell** [digipen-team-uwu/uwu-engine#10]
The singletons are hard to work with and lead to confusion with static variables everywhere. We should refactor them into traditional objects, and simply provide getters and setters for what was previously static in the engine.

Concerns include:
- Making sure syntax stays easy to use (no huge strings of getters)
- Making system maintenance/changes easier

**Comment by HardGaming01** [comment]
Possible Reference:
Chapter 5 of this book
https://www.gameenginebook.com/index.html

It would be nice to just make a static getter function in BaseSystem to get it self from the central system manager. So it'll be
`BaseSystem& Get();`
`TransformComponentManager::Get().GetTranslation()`
instead of 
`TransformComponentManager::GetTranslation()`
This keeps our base function call structure while making static objects into instances owned by the system manager

**Comment by zachrammell** [comment]
That's a nice and clean solution to the syntax problem, thanks!
